name: Build and deploy Jekyll site
on:
  push:
    branches: [ main ]
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
